import type { ProjectPageData } from "./types";

const asset = (path: string) => `/assets/projects/architecture-agent/${path}`;

export const architectureAgent: ProjectPageData = {
  slug: "architecture-agent",
  title: "Architecture Agent",
  subtitle:
    "Making AI recommendations easier to understand and act on - a usability test for the Architecture Agent.",
  projectType: "Usability Testing",
  timeline: "Jan 2026 - Mar 2026",
  bannerSrc: asset("actual-ai-preview.mp4"),
  bannerAlt: "Architecture Agent product preview",
  bannerType: "video",
  nav: [
    { id: "overview", label: "Overview", href: "#overview" },
    {
      id: "architecture-agent",
      label: "Architecture Agent",
      href: "#architecture-agent",
    },
    { id: "problem", label: "Problem", href: "#problem" },
    { id: "study-design", label: "Study Design", href: "#study-design" },
    { id: "finding-1", label: "Finding 1", href: "#finding-1" },
    { id: "finding-2", label: "Finding 2", href: "#finding-2" },
    { id: "reflection", label: "Reflections", href: "#reflection" },
  ],
  meta: {
    items: [
      { label: "Client", value: "Actual AI" },
      { label: "Timeline", value: "January 2026 - March 2026" },
      { label: "Team", value: "JP Nguyen, Sara Chong, Elnaz Melli, Nimesh Mohanakrishnan" },
      { label: "Role", value: "Design Researcher" },
    ],
  },
  overview: {
    eyebrow: "Overview",
    heading: "Making AI’s actions visible and understandable",
    paragraphs: [
      "Actual AI is a platform that helps engineering teams manage architecture and code quality in an era where both humans and AI agents are writing code. We partnered with their team through HCDE 517 to run a moderated usability study on one feature: the Architecture Agent, which surfaces and applies Architecture Decision Records (ADRs) across a codebase.",
      "Over five sessions with practicing software engineers and delivery managers, we found that people could generally follow the interface's structure, but consistently lost track of what the system had actually done at the moments that mattered most: right after accepting a change, and while that change was syncing in the background.",
      "This case study walks through three of our 29 findings in depth. A link to the full report is at the end.",
    ],
  },
  product: {
    eyebrow: "Architecture Agent",
    heading:
      "An ADR is a recommendation; a Context File is what makes that recommendation stick.",
    paragraphs: [
      "Before I get into what we found, it's worth explaining what architecture does and what an ADR is.",
      'The Architecture Agent is an AI agent that crawls a codebase, understands and spots technical architecture patterns, and proposes Architecture Decision Records, things like "adopt a consistent testing convention" or "standardize how environment configuration is handled." Architecture Decision Records (ADRs) are the architecture recommendations generated by the architecture agent.',
      "In the product, a user looks at each ADR and accepts, rejects, or archives it. Once someone accepts an ADR, it still has to make its way into the codebase's Context Files. These are the reference docs that AI coding tools (Claude, Cursor, Kiro, you name it) actually read before they touch any code, so that whatever gets built next follows the same rules. Getting an ADR into a Context File means the system generates a pull request, and a human still has to go review and merge it on GitHub.",
    ],
    workflow: {
      steps: [
        {
          id: "codebase",
          label: "Codebase",
          icon: "database",
          heading:
            "Existing codebase contains numerous technical patterns.",
        },
        {
          id: "read-patterns",
          label: "Read Patterns",
          icon: "workflow",
          heading: "Architecture agent reads those codebase patterns.",
        },
        {
          id: "create-add-rules",
          label: "Create & Add Rules",
          icon: "panels-top-left",
          heading:
            "Based on patterns observed, agent creates and adds rules to context files across tools.",
          tools: ["Cursor", "Claude Code", "Aider"],
        },
      ],
    },
  },
  problem: {
    eyebrow: "Problem",
    heading:
      "Actual AI needed to know if the Architecture Agent's recommendations were actually usable, not just automated.",
    paragraphs: [
      "The team didn't know whether developers could actually understand what the AI was recommending or confidently apply those recommendations without guidance. Our usability study focused on answering two questions:",
    ],
    items: [
      {
        id: "discover-interpret-act",
        title: "Discover, Interpret, Act",
        icon: "scan-search",
        content: {
          type: "paragraphs",
          paragraphs: [
            "Can users find, understand, and act on ADRs without guidance?",
          ],
        },
      },
      {
        id: "evaluate",
        title: "Evaluate",
        icon: "scale",
        content: {
          type: "paragraphs",
          paragraphs: [
            "How do users decide whether to accept, reject, or revert a decision, and what information do they lean on most to make that call?",
          ],
        },
      },
    ],
    imageSrc: asset("team-meeting.png"),
    imageAlt:
      "Research team and participant during a remote moderated usability session",
  },
  studyDesign: {
    eyebrow: "Study Design",
    heading:
      "Five 60-minute sessions, one shared test repo, and a research team that rotated roles every time.",
    paragraphs: [
      "We conducted five 60-minute moderated usability sessions using the same test organization and sample repository.",
      "Across sessions, our research team rotated between moderator, note-taker, and timekeeper. I independently moderated one complete session, while also contributing observations and synthesis across the study.",
      "We collected both behavioral and attitudinal data:"
    ],
    table: {
      headers: ["Participants", "Format", "Data Collected"],
      rows: [
        [
          "5 engineers & engineering managers",
          "60-min remote sessions",
          "Time on task",
        ],
        [
          "2–20 yrs experience",
          "Zoom, recorded w/ consent",
          "Likert ratings (ease, trust)",
        ],
        [
          "Recruited via screener survey",
          "Think-aloud protocol",
          "Interaction counts",
        ],
        ["-", "Shared test org + sample repo", "Post-task debrief"],
      ],
    },
    imageSrc: asset("group-pic.png"),
    imageAlt: "Architecture Agent research team group photo",
  },
  findings: [
    {
      id: "finding-1",
      eyebrow: "Finding 1",
      heading:
        "Developers could accept AI recommendations (ADRs), but couldn't confidently complete the workflow.",
      paragraphs: [
        "Every participant successfully located and accepted an Architecture Decision Record. However, accepting the recommendation created a second required step: synchronizing Context Files. Because this status appeared at the bottom of the page, participants interpreted the confirmation message as the end of the workflow and missed the remaining action entirely. Rather than failing to perform an interaction, participants failed to understand the system's current state.",
        "This finding directly answered the first research question. Participants could discover recommendations and act on them, but they could not reliably complete the workflow because the interface failed to communicate that another action was still required. The usability issue wasn't interaction — it was workflow visibility.",
      ],
      media: [
        {
          src: asset("finding-1.mp4"),
          alt: "Architecture Agent workflow showing Context File synchronization after accepting an ADR",
          type: "video",
          showBackground: false,
        },
      ],
      items: [
        {
          id: "finding-1-evidence",
          title: "Evidence",
          icon: "clipboard-list",
          content: {
            type: "paragraphs-with-list",
            intro: [],
            items: [
              "5 of 5 participants assumed accepting the ADR completed the task.",
              "Task completion time ranged from 3:18 to 12:08, depending on how quickly participants discovered the unsynchronized Context Files.",
            ],
          },
          quotes: [
            {
              text: "I feel like I've completed the test.",
              attribution: "Participant 3",
            },
            {
              text: "I would expect some sort of either a notification or some sort of progress indicator... to indicate the state of it.",
              attribution: "Participant 2",
            },
          ],
        },
        {
          id: "finding-1-design-recommendation",
          title: "Design Recommendation",
          icon: "lightbulb",
          content: {
            type: "paragraphs-with-list",
            intro: [
              "Based on our usability findings, we recommended making the synchronization step visible within the primary workflow so users could clearly understand what remained after accepting an ADR. Specifically, we proposed:",
            ],
            items: [
              "Surface Context File synchronization immediately after accepting an ADR.",
              "Clearly communicate synchronization status and required next steps through persistent workflow feedback.",
            ],
          },
        },
        {
          id: "finding-1-production-outcome",
          title: "Production Outcome",
          icon: "sparkles",
          content: {
            type: "paragraphs",
            paragraphs: [
              "Following the study, Actual AI removed the manual Context File synchronization step from the workflow. After developers accept an ADR, Context Files are now generated automatically in the background, allowing users to review the resulting pull request directly in their codebase before merging. By eliminating an entire step, the updated workflow reduces the ambiguity observed during testing and makes architectural decisions feel complete once accepted.",
            ],
          },
          media: [
            {
              src: asset("production-1.mp4"),
              alt: "Production Architecture Agent workflow after accepting an ADR, with Context Files generated automatically",
              type: "video",
              showBackground: false,
            },
          ],
        },
      ],
    },
    {
      id: "finding-2",
      eyebrow: "Finding 2",
      heading:
        "Developers struggled to build a mental model of the Architecture Agent before completing tasks.",
      paragraphs: [
        "Before participants could evaluate Architecture Decision Records, they first had to understand how the Architecture Agent itself worked. Across sessions, participants spent considerable time exploring the interface, asking clarifying questions, and trying to infer relationships between Repositories, Categories, Decisions, Context Files, and pull requests. Rather than learning through the interface itself, participants relied on the moderator's explanations to understand the workflow.",
        "This wasn't simply unfamiliarity with a new product. The Architecture Agent introduces concepts—such as ADRs and Context Files—that are unique to Actual AI and have no established mental model for most developers. Without guidance, participants entered the tasks with an incomplete understanding of how the system was organized. That increased cognitive load before meaningful work could begin.",
      ],
      media: [
        {
          src: asset("annotated.jpg"),
          alt: "Annotated Architecture Agent interface showing where developers struggled to form a mental model",
          showBackground: true,
        },
      ],
      items: [
        {
          id: "finding-2-evidence",
          title: "Evidence",
          icon: "clipboard-list",
          content: {
            type: "paragraphs-with-list",
            intro: [],
            items: [
              "2 of 5 participants explicitly identified terminology as an overall usability issue during the post-test debrief.",
              "Ease ratings ranged from 2–5/5. The participants giving the lowest rating (2–3/5) specifically attributed it to terminology.",
            ],
          },
          quotes: [
            {
              text: "Took a bit to make the link between 'Decision' and recommendations.",
              attribution: "Participant 4",
            },
            {
              text: "Like, tools that, as you first open up a new page, they can walk you through how to use the experience.",
              attribution: "Participant 2",
            },
          ],
        },
        {
          id: "finding-2-design-recommendation",
          title: "Design Recommendation",
          icon: "lightbulb",
          content: {
            type: "paragraphs-with-list",
            intro: [
              "Rather than introducing every feature upfront, we recommended progressive onboarding that helps developers form a mental model while they explore. Specifically:",
            ],
            items: [
              "Introduce a first-run walkthrough explaining the Architecture Agent workflow.",
              "Provide contextual explanations for concepts such as ADRs and Context Files.",
              "Use progressive disclosure so information appears when it becomes relevant.",
            ],
          },
        },
        {
          id: "finding-2-production-outcome",
          title: "Production Outcome",
          icon: "sparkles",
          content: {
            type: "paragraphs-with-list",
            intro: ["Based on my observations, I provided 2 recommendations:"],
            items: [
              "Move Context File status directly into the primary workflow, making synchronization the obvious next step after accepting an ADR.",
              "Remove the context files entirely and make the ADR acceptance an automated experience.",
            ],
          },
        },
      ],
    },
  ],
  reflection: {
    eyebrow: "Reflections",
    heading: "What I learned from this project",
    paragraphs: [],
    items: [
      {
        id: "ai-products-communicate-state",
        title: "AI products need to communicate state, not just output.",
        icon: "activity",
        content: {
          type: "paragraphs",
          paragraphs: [
            "Working on an AI product made me realize that good AI UX isn't only about explaining the model's output. Users also need to understand what the system is doing between actions. In the Architecture Agent, the recommendation itself was understandable enough; what became confusing was what happened after accepting it. That made system state feel like a much more important part of AI interaction design than I had previously considered.",
          ],
        },
      },
      {
        id: "task-phrasing-matters",
        title: "Task phrasing matters more than I initially realized",
        icon: "type",
        content: {
          type: "paragraphs",
          paragraphs: [
            "Our original Task 2 asked participants to find “architectural recommendations you care about.” After P1 and P2 struggled with the task, we realized the phrasing itself was ambiguous and changed it to “find specific architectural recommendations.” The next three participants completed the task successfully.",
            "This reinforced the value of pilot testing the study design itself. Small wording choices can influence what participants understand—and ultimately, what you're measuring.",
          ],
        },
      },
    ],
  },
};
